# AIOS Tools Index

Note: This file is generated by runtime_intelligence/tools/index_tools.py.
Run the VS Code task "Generate Tools Index" to refresh.

- Central tools (cross-cutting): runtime_intelligence/tools
- Module tools (locality): ai/tools, core/tools, interface/tools


## central tools

Path: `runtime_intelligence/tools`

- runtime_intelligence/tools/__pycache__/system_health_check.cpython-312.pyc
- runtime_intelligence/tools/aios_admin.py
- runtime_intelligence/tools/index_tools.py
- runtime_intelligence/tools/README.md
- runtime_intelligence/tools/self_similarity_analyzer.py
- runtime_intelligence/tools/system_health_check.py
- runtime_intelligence/tools/system_status_report.py

## ai tools

Path: `ai/tools`

- ai/tools/__init__.py
- ai/tools/aios_context_registry_validator.py
- ai/tools/comprehensive_e501_fix.py
- ai/tools/fix_e501_.py
- ai/tools/ga_perl/ga.pl
- ai/tools/ga_perl/README.md
- ai/tools/ga_perl/run_ga.ps1
- ai/tools/README.md

## duplicates

- README.md
  - ai/tools/README.md
  - ai/tools/ga_perl/README.md
  - runtime_intelligence/tools/README.md

