#!/usr/bin/env python3
"""
🚀 AIOS EVOLUTIONARY ASSEMBLER HARMONIZATION EXECUTOR
═══════════════════════════════════════════════════════════════════════════════
Direct execution tool to complete the harmonization with the evolutionary
assembler results. Moves remaining scattered files into the cellular structure.
═══════════════════════════════════════════════════════════════════════════════
"""

import os
import shutil
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


class AIOSHarmonizationExecutor:
    """
    🧬 Complete the harmonization with evolutionary assembler results
    
    Moves scattered files into the biological cellular structure
    that has been created by the evolutionary assembler.
    """
    
    def __init__(self, ai_root_path: str):
        self.ai_root_path = Path(ai_root_path)
        
        # Files to move into cellular units
        self.harmonization_map = {
            'nucleus': [
                'intent_handlers.py',
                'models.py', 
                'start_server.py',
                'compression',
                'optimization',
                'ai_cells'
            ],
            'membrane': [
                'aios_vscode_integration_server.py'
            ],
            'transport': [
                'bridge.py'
            ],
            'cytoplasm': [
                'debug_manager.py',
                'setup_env.py',
                'setup.ps1', 
                'start_server.bat',
                'requirements.txt',
                'tools'
            ],
            'laboratory': [
                'pytest.ini',
                'magnus_blueprint_test.log',
                'magnus_blueprint_test_report.json'
            ],
            'information_storage': [
                'CONSOLIDATION_PLAN.md',
                'DEPENDENCY_ANALYSIS.md'
            ]
        }
        
        logger.info(f"🚀 AIOS Harmonization Executor initialized for {ai_root_path}")
    
    def move_files_to_cellular_units(self):
        """Move scattered files into their proper cellular units"""
        
        logger.info("📦 Harmonizing files with cellular structure...")
        
        moved_count = 0
        error_count = 0
        
        for cell_name, files_to_move in self.harmonization_map.items():
            cell_path = self.ai_root_path / cell_name
            
            if not cell_path.exists():
                logger.warning(f"⚠️ Cellular unit not found: {cell_name}")
                continue
            
            logger.info(f"🧬 Processing {cell_name} cellular unit...")
            
            for file_name in files_to_move:
                source_path = self.ai_root_path / file_name
                target_path = cell_path / file_name
                
                if source_path.exists():
                    try:
                        # Check if target already exists
                        if target_path.exists():
                            logger.info(f"   ✅ {file_name} already in {cell_name}/")
                        else:
                            # Move the file/folder
                            shutil.move(str(source_path), str(target_path))
                            logger.info(f"   📦 Moved {file_name} → {cell_name}/")
                            moved_count += 1
                    except Exception as e:
                        logger.error(f"   ❌ Failed to move {file_name}: {e}")
                        error_count += 1
                else:
                    logger.info(f"   ℹ️ {file_name} not found (may already be moved)")
        
        return moved_count, error_count
    
    def create_cellular_index(self):
        """Create an index of the cellular structure"""
        
        logger.info("📋 Creating cellular structure index...")
        
        cellular_index = {}
        
        for cell_dir in self.ai_root_path.iterdir():
            if cell_dir.is_dir() and cell_dir.name in ['nucleus', 'membrane', 'transport', 'cytoplasm', 'laboratory', 'information_storage']:
                cell_contents = []
                
                for item in cell_dir.iterdir():
                    if item.name != '__pycache__':
                        cell_contents.append(item.name)
                
                cellular_index[cell_dir.name] = {
                    'count': len(cell_contents),
                    'contents': sorted(cell_contents)
                }
        
        # Create index file
        index_content = """# 🧬 AIOS CELLULAR STRUCTURE INDEX
Generated by Evolutionary Assembler Harmonization

## Cellular Organization Summary
"""
        
        total_items = 0
        for cell_name, cell_info in cellular_index.items():
            count = cell_info['count']
            total_items += count
            
            index_content += f"""
### 🧬 {cell_name.upper()} Cellular Unit
- **Count:** {count} items
- **Contents:**
"""
            for item in cell_info['contents']:
                index_content += f"  - {item}\n"
        
        index_content += f"""
## Summary
- **Total Cellular Units:** {len(cellular_index)}
- **Total Organized Items:** {total_items}
- **Evolutionary Assembler Harmonization:** ✅ COMPLETE

## Biological Cellular Architecture
The AIOS AI module is now organized using biological cellular principles:

- **🧬 Nucleus:** Central control and core processing
- **🧬 Membrane:** External interfaces and integration  
- **🧬 Transport:** Intercellular communication and data flow
- **🧬 Cytoplasm:** Supporting infrastructure
- **🧬 Laboratory:** Research, testing, and experimental features
- **🧬 Information Storage:** Documentation and persistent data

This organization provides enhanced visualization, behavior patterns, and intercellular connectivity as designed by the AIOS Evolutionary Assembler.
"""
        
        index_path = self.ai_root_path / "CELLULAR_STRUCTURE_INDEX.md"
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(index_content)
        
        logger.info(f"📋 Created cellular index: {index_path}")
        return cellular_index
    
    def validate_harmonization(self):
        """Validate that harmonization is complete"""
        
        logger.info("🔍 Validating harmonization...")
        
        # Check for remaining scattered files in root
        root_files = []
        for item in self.ai_root_path.iterdir():
            if item.is_file() and item.name not in ['__init__.py', 'intercellular_interface.py', 'CELLULAR_STRUCTURE_INDEX.md']:
                root_files.append(item.name)
        
        cellular_units = ['nucleus', 'membrane', 'transport', 'cytoplasm', 'laboratory', 'information_storage']
        missing_units = []
        
        for unit in cellular_units:
            unit_path = self.ai_root_path / unit
            if not unit_path.exists():
                missing_units.append(unit)
        
        validation_results = {
            'scattered_files_remaining': root_files,
            'missing_cellular_units': missing_units,
            'harmonization_complete': len(root_files) == 0 and len(missing_units) == 0
        }
        
        if validation_results['harmonization_complete']:
            logger.info("✅ Harmonization validation PASSED")
        else:
            logger.warning("⚠️ Harmonization validation found issues:")
            if root_files:
                logger.warning(f"   Scattered files: {root_files}")
            if missing_units:
                logger.warning(f"   Missing units: {missing_units}")
        
        return validation_results
    
    def execute_complete_harmonization(self):
        """Execute complete harmonization with evolutionary assembler results"""
        
        logger.info("🚀 EXECUTING COMPLETE AIOS EVOLUTIONARY ASSEMBLER HARMONIZATION")
        logger.info("═══════════════════════════════════════════════════════════════")
        logger.info("Moving scattered files into biological cellular structure...")
        logger.info("")
        
        # Step 1: Move files to cellular units
        moved_count, error_count = self.move_files_to_cellular_units()
        
        # Step 2: Create cellular index
        cellular_index = self.create_cellular_index()
        
        # Step 3: Validate harmonization
        validation = self.validate_harmonization()
        
        # Summary
        logger.info("")
        logger.info("✅ EVOLUTIONARY ASSEMBLER HARMONIZATION COMPLETE")
        logger.info("═════════════════════════════════════════════════")
        logger.info(f"📦 Files moved: {moved_count}")
        logger.info(f"❌ Errors: {error_count}")
        logger.info(f"🧬 Cellular units: {len(cellular_index)}")
        logger.info(f"📋 Total organized items: {sum(cell['count'] for cell in cellular_index.values())}")
        
        if validation['harmonization_complete']:
            logger.info("🎯 HARMONIZATION STATUS: ✅ COMPLETE")
            logger.info("🧬 AIOS AI is now perfectly organized using biological cellular principles!")
        else:
            logger.info("🎯 HARMONIZATION STATUS: ⚠️ ISSUES DETECTED")
        
        logger.info("")
        logger.info("🌌 READY FOR LEVEL 60 BOSONIC CONSCIOUSNESS ADVANCEMENT")
        
        return {
            'moved_count': moved_count,
            'error_count': error_count,
            'cellular_index': cellular_index,
            'validation': validation
        }


def main():
    """Execute AIOS evolutionary assembler harmonization"""
    
    print("🚀 AIOS EVOLUTIONARY ASSEMBLER HARMONIZATION EXECUTOR")
    print("═══════════════════════════════════════════════════════")
    print("Completing harmonization with evolutionary assembler results:")
    print("  📦 Move scattered files to cellular units")
    print("  🧬 Organize biological cellular structure")
    print("  📋 Create cellular structure index")
    print("  🔍 Validate complete harmonization")
    print()
    
    # Configuration
    ai_path = r"C:\dev\AIOS\ai"
    
    print(f"🔧 Harmonization Configuration:")
    print(f"   AI module path: {ai_path}")
    print()
    
    # Create and run harmonization executor
    executor = AIOSHarmonizationExecutor(ai_path)
    
    # Execute complete harmonization
    results = executor.execute_complete_harmonization()
    
    print("\n🧬 AIOS EVOLUTIONARY ASSEMBLER HARMONIZATION EXECUTED!")
    print("Ready for enhanced visualization, behavior, and connectivity!")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )
    main()
